//! Deterministic golden vectors generated by Renee's real wire encoders.

#![forbid(unsafe_code)]
#![allow(
    clippy::big_endian_bytes,
    reason = "malformed wire vectors construct canonical network-order prefixes directly"
)]

use core::fmt;

use renee_types::{
    AcceptanceSequence, Authenticator, CapabilityId, CreateAuthorityId, DocumentId,
    ImmutableUpdate, LoroRange, Operation, OperationSet, PublicLoroRanges, RequestId, UpdateId,
    UpdateMetadata,
};
use renee_wire::{
    ACCEPT_UPDATE, ACCEPT_UPDATE_RESPONSE, AcceptUpdateOutcome, AcceptanceCursor,
    AuthorizedUpdateRequest, CANCEL_UPDATE_SUBSCRIPTION, CANCEL_UPDATE_SUBSCRIPTION_RESPONSE,
    CAPABILITY_ERROR, CERTIFICATE_MANIFEST, CERTIFICATE_MANIFEST_RESPONSE, CLIENT_HELLO,
    CREATE_DOCUMENT, CREATE_DOCUMENT_RESPONSE, CapabilityAuthority, CapabilityErrorCode,
    ControlMutationOutcome, CreateAuthority, CreateDocumentOutcome, CreateDocumentRequest,
    ENUMERATE_UPDATES, ENUMERATE_UPDATES_RESPONSE, ERROR_ALREADY_NEGOTIATED, ERROR_EXPECTED_HELLO,
    ERROR_MALFORMED_HELLO, ERROR_UNSUPPORTED_PROFILE, ERROR_UNSUPPORTED_VERSION, EnumerateRequest,
    EnumerateResponse, EnumerateStart, Envelope, FETCH_UPDATE, FETCH_UPDATE_RESPONSE, FetchRequest,
    GRANT_CAPABILITY, GRANT_CAPABILITY_RESPONSE, GrantCapabilityRequest,
    MAX_APPLICATION_PAYLOAD_LENGTH, PROFILE, PROTOCOL_ERROR, REVOKE_CAPABILITY,
    REVOKE_CAPABILITY_RESPONSE, RevokeCapabilityRequest, SERVER_HELLO, SUBSCRIBE_UPDATES,
    SUBSCRIBE_UPDATES_ACK, SubscribeUpdatesRequest, UPDATE_ERROR, UPDATE_NOTIFICATION,
    UPDATE_SUBSCRIPTION_OVERFLOW, UpdateErrorCode, UpdateNotification, UpdateSubscriptionId,
    VERSION, encode_accept_response, encode_acceptance_cursor, encode_authorized_update_request,
    encode_cancel_update_subscription, encode_capability_error, encode_control_mutation_response,
    encode_create_document_request, encode_create_document_response, encode_enumerate_request,
    encode_enumerate_response, encode_fetch_request, encode_fetch_response, encode_frame,
    encode_grant_capability_request, encode_greeting, encode_revoke_capability_request,
    encode_subscribe_updates_ack, encode_subscribe_updates_request, encode_update_error,
    encode_update_notification, encode_update_record, encode_update_subscription_overflow,
};
use ring::signature::{Ed25519KeyPair, KeyPair as _};

const CARBON_BANNER: &str = "I couldn't stay away";
const RENEE_BANNER: &str = "I've been expecting you";
const SCHEMA: &str = "renee-wire-golden-v1";

struct FrameVector {
    category: &'static str,
    correlation_id: [u8; 16],
    frame: Vec<u8>,
    message_type: u16,
    name: &'static str,
    payload: Vec<u8>,
}

struct InvalidFrameVector {
    expected_error: &'static str,
    frame: Vec<u8>,
    name: &'static str,
}

struct InvalidPayloadVector {
    expected_error: &'static str,
    frame: FrameVector,
}

/// Generates the canonical JSON corpus.
#[expect(
    clippy::too_many_lines,
    reason = "keeping the ordered golden corpus in one function makes omissions and reorderings reviewable"
)]
pub fn generate() -> Result<String, GenerateError> {
    let document_id = DocumentId::from_bytes([0x33; 16]);
    let update_id = UpdateId::from_bytes([0x44; 16]);
    let update = fixture_update(document_id, update_id)?;
    let record = encode_update_record(&update)?;
    let root = CapabilityAuthority {
        capability_id: CapabilityId::from_bytes([0x55; 16]),
        authenticator: Authenticator::from_bytes([0x56; 32]),
    };
    let editor = CapabilityAuthority {
        capability_id: CapabilityId::from_bytes([0x57; 16]),
        authenticator: Authenticator::from_bytes([0x58; 32]),
    };
    let create_authority = CreateAuthority {
        create_authority_id: CreateAuthorityId::from_bytes([0x53; 16]),
        authenticator: Authenticator::from_bytes([0x54; 32]),
    };
    let cursor = encode_acceptance_cursor(
        document_id,
        AcceptanceCursor {
            position: AcceptanceSequence::FIRST,
            terminal_sequence: AcceptanceSequence::from_be_bytes([0, 0, 0, 0, 0, 0, 0, 3]),
        },
    )?;
    let metadata = UpdateMetadata {
        encrypted_payload_length: u32::try_from(update.encrypted_payload().len())
            .map_err(|error| GenerateError::new(error.to_string()))?,
        public_loro_ranges: update.public_loro_ranges().clone(),
        update_id,
    };
    let (certificate_manifest, control_public_key) = certificate_manifest_fixture()?;
    let subscription_id = UpdateSubscriptionId::from_bytes([0x60; 16]);

    let mut frames = vec![
        frame(
            "hello.client",
            "hello",
            CLIENT_HELLO,
            0x11,
            encode_greeting(PROFILE, CARBON_BANNER)?,
        )?,
        frame(
            "hello.server",
            "hello",
            SERVER_HELLO,
            0x11,
            encode_greeting(PROFILE, RENEE_BANNER)?,
        )?,
        frame(
            "certificate-manifest.request",
            "credentials",
            CERTIFICATE_MANIFEST,
            0x18,
            Vec::new(),
        )?,
        frame(
            "certificate-manifest.response",
            "credentials",
            CERTIFICATE_MANIFEST_RESPONSE,
            0x18,
            certificate_manifest.clone(),
        )?,
        frame(
            "document.create.request",
            "capability",
            CREATE_DOCUMENT,
            0x20,
            encode_create_document_request(&CreateDocumentRequest {
                create_authority,
                request_id: RequestId::from_bytes([0x52; 16]),
                document_id,
                root: root.clone(),
            }),
        )?,
        frame(
            "document.create.response.inserted",
            "capability",
            CREATE_DOCUMENT_RESPONSE,
            0x20,
            encode_create_document_response(CreateDocumentOutcome::Inserted),
        )?,
        frame(
            "document.create.response.already-present",
            "capability",
            CREATE_DOCUMENT_RESPONSE,
            0x20,
            encode_create_document_response(CreateDocumentOutcome::AlreadyPresent),
        )?,
        frame(
            "capability.grant.request",
            "capability",
            GRANT_CAPABILITY,
            0x21,
            encode_grant_capability_request(&GrantCapabilityRequest {
                document_id,
                issuer: root.clone(),
                request_id: RequestId::from_bytes([0x59; 16]),
                descendant: editor.clone(),
                operations: OperationSet::one(Operation::Update),
            }),
        )?,
        frame(
            "capability.grant.response.inserted",
            "capability",
            GRANT_CAPABILITY_RESPONSE,
            0x21,
            encode_control_mutation_response(ControlMutationOutcome::Inserted),
        )?,
        frame(
            "capability.grant.response.already-present",
            "capability",
            GRANT_CAPABILITY_RESPONSE,
            0x21,
            encode_control_mutation_response(ControlMutationOutcome::AlreadyPresent),
        )?,
        frame(
            "capability.revoke.request",
            "capability",
            REVOKE_CAPABILITY,
            0x23,
            encode_revoke_capability_request(&RevokeCapabilityRequest {
                document_id,
                issuer: root.clone(),
                request_id: RequestId::from_bytes([0x5a; 16]),
                target_capability_id: editor.capability_id,
            }),
        )?,
        frame(
            "capability.revoke.response.inserted",
            "capability",
            REVOKE_CAPABILITY_RESPONSE,
            0x23,
            encode_control_mutation_response(ControlMutationOutcome::Inserted),
        )?,
        frame(
            "capability.revoke.response.already-present",
            "capability",
            REVOKE_CAPABILITY_RESPONSE,
            0x23,
            encode_control_mutation_response(ControlMutationOutcome::AlreadyPresent),
        )?,
        frame(
            "accept.request.authorized",
            "accept",
            ACCEPT_UPDATE,
            0x22,
            encode_authorized_update_request(&AuthorizedUpdateRequest {
                authority: root.clone(),
                encoded_record: &record,
            })?,
        )?,
        frame(
            "accept.response.inserted",
            "accept",
            ACCEPT_UPDATE_RESPONSE,
            0x22,
            encode_accept_response(AcceptUpdateOutcome::Inserted),
        )?,
        frame(
            "accept.response.already-present",
            "accept",
            ACCEPT_UPDATE_RESPONSE,
            0x22,
            encode_accept_response(AcceptUpdateOutcome::AlreadyPresent),
        )?,
        frame(
            "enumerate.request.origin",
            "enumerate",
            ENUMERATE_UPDATES,
            0x31,
            encode_enumerate_request(&EnumerateRequest {
                authority: root.clone(),
                document_id,
                start: EnumerateStart::Origin,
            })?,
        )?,
        frame(
            "enumerate.request.continue",
            "enumerate",
            ENUMERATE_UPDATES,
            0x32,
            encode_enumerate_request(&EnumerateRequest {
                authority: root.clone(),
                document_id,
                start: EnumerateStart::Continue(cursor.clone()),
            })?,
        )?,
        frame(
            "enumerate.request.after-tail",
            "enumerate",
            ENUMERATE_UPDATES,
            0x33,
            encode_enumerate_request(&EnumerateRequest {
                authority: root.clone(),
                document_id,
                start: EnumerateStart::AfterTail(cursor.clone()),
            })?,
        )?,
        frame(
            "enumerate.response.page",
            "enumerate",
            ENUMERATE_UPDATES_RESPONSE,
            0x31,
            encode_enumerate_response(&EnumerateResponse {
                has_more: true,
                next_cursor: Some(cursor),
                updates: vec![metadata],
            })?,
        )?,
        frame(
            "enumerate.response.empty",
            "enumerate",
            ENUMERATE_UPDATES_RESPONSE,
            0x34,
            encode_enumerate_response(&EnumerateResponse {
                has_more: false,
                next_cursor: None,
                updates: Vec::new(),
            })?,
        )?,
        frame(
            "fetch.request",
            "fetch",
            FETCH_UPDATE,
            0x41,
            encode_fetch_request(&FetchRequest { authority: root.clone(), document_id, update_id }),
        )?,
        frame(
            "fetch.response",
            "fetch",
            FETCH_UPDATE_RESPONSE,
            0x41,
            encode_fetch_response(update.encrypted_payload())?,
        )?,
        frame(
            "subscription.request",
            "subscription",
            SUBSCRIBE_UPDATES,
            0x42,
            encode_subscribe_updates_request(&SubscribeUpdatesRequest {
                authority: root.clone(),
                document_id,
            }),
        )?,
        frame(
            "subscription.acknowledgement",
            "subscription",
            SUBSCRIBE_UPDATES_ACK,
            0x42,
            encode_subscribe_updates_ack(subscription_id),
        )?,
        frame(
            "subscription.notification",
            "subscription",
            UPDATE_NOTIFICATION,
            0x42,
            encode_update_notification(UpdateNotification { subscription_id, update_id }),
        )?,
        frame(
            "subscription.overflow",
            "subscription",
            UPDATE_SUBSCRIPTION_OVERFLOW,
            0x42,
            encode_update_subscription_overflow(subscription_id),
        )?,
        frame(
            "subscription.cancel.request",
            "subscription",
            CANCEL_UPDATE_SUBSCRIPTION,
            0x43,
            encode_cancel_update_subscription(subscription_id),
        )?,
        frame(
            "subscription.cancel.response",
            "subscription",
            CANCEL_UPDATE_SUBSCRIPTION_RESPONSE,
            0x43,
            encode_cancel_update_subscription(subscription_id),
        )?,
    ];

    for (name, payload) in [
        ("error.protocol.unsupported-version", ERROR_UNSUPPORTED_VERSION),
        ("error.protocol.unsupported-profile", ERROR_UNSUPPORTED_PROFILE),
        ("error.protocol.expected-hello", ERROR_EXPECTED_HELLO),
        ("error.protocol.already-negotiated", ERROR_ALREADY_NEGOTIATED),
        ("error.protocol.malformed-hello", ERROR_MALFORMED_HELLO),
    ] {
        frames.push(frame(name, "errors", PROTOCOL_ERROR, 0x50, payload.to_vec())?);
    }
    for (name, error) in [
        ("error.update.malformed", UpdateErrorCode::Malformed),
        ("error.update.identifier-conflict", UpdateErrorCode::IdentifierConflict),
        ("error.update.not-found", UpdateErrorCode::NotFound),
        ("error.update.not-negotiated", UpdateErrorCode::NotNegotiated),
        ("error.update.invalid-cursor", UpdateErrorCode::InvalidCursor),
        ("error.update.counter-exhausted", UpdateErrorCode::CounterExhausted),
        ("error.update.authorization-denied", UpdateErrorCode::AuthorizationDenied),
        ("error.update.backpressure", UpdateErrorCode::Backpressure),
    ] {
        frames.push(frame(name, "errors", UPDATE_ERROR, 0x51, encode_update_error(error))?);
    }
    for (name, error) in [
        ("error.capability.malformed", CapabilityErrorCode::Malformed),
        ("error.capability.authorization-denied", CapabilityErrorCode::AuthorizationDenied),
        ("error.capability.identifier-conflict", CapabilityErrorCode::IdentifierConflict),
        ("error.capability.request-conflict", CapabilityErrorCode::RequestConflict),
        ("error.capability.counter-exhausted", CapabilityErrorCode::CounterExhausted),
        ("error.capability.limit-exceeded", CapabilityErrorCode::LimitExceeded),
    ] {
        frames.push(frame(name, "errors", CAPABILITY_ERROR, 0x52, encode_capability_error(error))?);
    }

    let maximum_greeting_field = "p".repeat(256);
    frames.push(frame(
        "limit.maximum-greeting-fields",
        "limits",
        CLIENT_HELLO,
        0x61,
        encode_greeting(&maximum_greeting_field, &"b".repeat(256))?,
    )?);
    let maximum_record = maximum_update_record(document_id, UpdateId::from_bytes([0x66; 16]))?;
    frames.push(frame(
        "limit.maximum-application-payload",
        "limits",
        ACCEPT_UPDATE,
        0x62,
        encode_authorized_update_request(&AuthorizedUpdateRequest {
            authority: root,
            encoded_record: &maximum_record,
        })?,
    )?);

    let oversized_greeting = oversized_greeting_payload();
    let mut invalid_payloads = vec![InvalidPayloadVector {
        expected_error: "greeting-field-too-long",
        frame: frame(
            "limit.oversized-greeting-field",
            "limits",
            CLIENT_HELLO,
            0x63,
            oversized_greeting,
        )?,
    }];
    invalid_payloads.push(InvalidPayloadVector {
        expected_error: "subscription-payload-truncated",
        frame: frame(
            "subscription.request.truncated",
            "subscription",
            SUBSCRIBE_UPDATES,
            0x64,
            vec![0, 1, 0],
        )?,
    });
    let mut wrong_subscription_version = encode_cancel_update_subscription(subscription_id);
    wrong_subscription_version[1] ^= 1;
    invalid_payloads.push(InvalidPayloadVector {
        expected_error: "unsupported-subscription-payload-version",
        frame: frame(
            "subscription.cancel.wrong-version",
            "subscription",
            CANCEL_UPDATE_SUBSCRIPTION,
            0x65,
            wrong_subscription_version,
        )?,
    });
    let invalid_frames = invalid_frame_vectors(frames.first().ok_or_else(|| {
        GenerateError::new("golden frame corpus unexpectedly has no first vector")
    })?)?;

    Ok(render(
        &frames,
        &invalid_payloads,
        &invalid_frames,
        &control_public_key,
        &certificate_manifest,
    ))
}

fn certificate_manifest_fixture() -> Result<(Vec<u8>, [u8; 32]), GenerateError> {
    let control = Ed25519KeyPair::from_seed_unchecked(&[0x7a; 32])
        .map_err(|_error| GenerateError::new("fixed Ed25519 control key is invalid"))?;
    let control_public_key =
        control.public_key().as_ref().try_into().map_err(|_error| {
            GenerateError::new("fixed Ed25519 public key has an invalid length")
        })?;
    let mut manifest = Vec::with_capacity(178);
    manifest.extend_from_slice(b"RNECERT\0");
    manifest.extend_from_slice(&1_u16.to_be_bytes());
    encode_certificate_epoch(&mut manifest, 1, 2_000_000_000, 0x11);
    encode_certificate_epoch(&mut manifest, 2, 2_000_604_800, 0x22);
    manifest.extend_from_slice(control.sign(&manifest).as_ref());
    Ok((manifest, control_public_key))
}

fn encode_certificate_epoch(encoded: &mut Vec<u8>, epoch: u32, not_before: i64, hash_byte: u8) {
    encoded.extend_from_slice(&epoch.to_be_bytes());
    encoded.extend_from_slice(&not_before.to_be_bytes());
    encoded.extend_from_slice(&(not_before + 1_209_600).to_be_bytes());
    encoded.extend(core::iter::repeat_n(hash_byte, 32));
}

fn fixture_update(
    document_id: DocumentId,
    update_id: UpdateId,
) -> Result<ImmutableUpdate, GenerateError> {
    let ranges = PublicLoroRanges::new(vec![
        LoroRange::new(0x0102_0304_0506_0708, 0, 3)?,
        LoroRange::new(0x1112_1314_1516_1718, 4, 9)?,
    ])?;
    Ok(ImmutableUpdate::new(document_id, update_id, ranges, b"opaque-ciphertext-v1".to_vec()))
}

fn maximum_update_record(
    document_id: DocumentId,
    update_id: UpdateId,
) -> Result<Vec<u8>, GenerateError> {
    let ranges = PublicLoroRanges::new(vec![LoroRange::new(0x7172_7374_7576_7778, 0, 1)?])?;
    let minimum = encode_update_record(&ImmutableUpdate::new(
        document_id,
        update_id,
        ranges.clone(),
        vec![0xa5],
    ))?;
    let overhead = minimum
        .len()
        .checked_sub(1)
        .ok_or_else(|| GenerateError::new("minimum update record has no payload byte"))?;
    let payload_length = MAX_APPLICATION_PAYLOAD_LENGTH
        .checked_sub(16 + 32)
        .ok_or_else(|| GenerateError::new("authority overhead exceeds application limit"))?
        .checked_sub(overhead)
        .ok_or_else(|| GenerateError::new("update record overhead exceeds application limit"))?;
    let encoded = encode_update_record(&ImmutableUpdate::new(
        document_id,
        update_id,
        ranges,
        vec![0xa5; payload_length],
    ))?;
    if encoded.len() + 16 + 32 != MAX_APPLICATION_PAYLOAD_LENGTH {
        return Err(GenerateError::new(
            "maximum authorized update does not fill one application payload",
        ));
    }
    Ok(encoded)
}

fn frame(
    name: &'static str,
    category: &'static str,
    message_type: u16,
    correlation_byte: u8,
    payload: Vec<u8>,
) -> Result<FrameVector, GenerateError> {
    let correlation_id = [correlation_byte; 16];
    let envelope =
        Envelope { correlation_id, message_type, payload: payload.clone(), version: VERSION };
    let encoded = encode_frame(&envelope)?;
    Ok(FrameVector { category, correlation_id, frame: encoded, message_type, name, payload })
}

fn oversized_greeting_payload() -> Vec<u8> {
    let mut payload = Vec::with_capacity(263);
    payload.extend_from_slice(&257_u16.to_be_bytes());
    payload.extend(core::iter::repeat_n(b'p', 257));
    payload.extend_from_slice(&0_u16.to_be_bytes());
    payload
}

fn invalid_frame_vectors(hello: &FrameVector) -> Result<Vec<InvalidFrameVector>, GenerateError> {
    let mut invalid_magic = hello.frame.clone();
    let magic = invalid_magic
        .get_mut(4)
        .ok_or_else(|| GenerateError::new("hello frame has no magic byte"))?;
    *magic ^= 0xff;

    let mut truncated_body = hello.frame.clone();
    truncated_body.pop().ok_or_else(|| GenerateError::new("hello frame cannot be truncated"))?;

    let mut trailing = hello.frame.clone();
    trailing.push(0xff);

    let mut short_envelope = Vec::with_capacity(27);
    short_envelope.extend_from_slice(&23_u32.to_be_bytes());
    short_envelope.extend(core::iter::repeat_n(0_u8, 23));

    let oversized_length = u32::try_from(renee_wire::MAX_BODY_LENGTH)
        .map_err(|error| GenerateError::new(error.to_string()))?
        .checked_add(1)
        .ok_or_else(|| GenerateError::new("maximum body length cannot advance"))?;

    Ok(vec![
        invalid("malformed.empty-stream", "truncated-frame", Vec::new()),
        invalid("malformed.partial-prefix-1", "truncated-frame", vec![0]),
        invalid("malformed.partial-prefix-2", "truncated-frame", vec![0, 0]),
        invalid("malformed.partial-prefix-3", "truncated-frame", vec![0, 0, 0]),
        invalid("malformed.zero-length-body", "malformed-envelope", 0_u32.to_be_bytes().to_vec()),
        invalid("malformed.short-envelope", "malformed-envelope", short_envelope),
        invalid("malformed.truncated-body", "truncated-frame", truncated_body),
        invalid(
            "malformed.oversized-length",
            "frame-too-long",
            oversized_length.to_be_bytes().to_vec(),
        ),
        invalid("malformed.invalid-magic", "malformed-envelope", invalid_magic),
        invalid("malformed.trailing-byte", "trailing-bytes", trailing),
    ])
}

fn invalid(name: &'static str, expected_error: &'static str, frame: Vec<u8>) -> InvalidFrameVector {
    InvalidFrameVector { expected_error, frame, name }
}

fn render(
    frames: &[FrameVector],
    invalid_payloads: &[InvalidPayloadVector],
    invalid_frames: &[InvalidFrameVector],
    control_public_key: &[u8],
    certificate_manifest: &[u8],
) -> String {
    let mut output = String::new();
    output.push_str("{\n  \"schema\": \"");
    output.push_str(SCHEMA);
    output.push_str("\",\n  \"max_body_length\": 4096,\n");
    output.push_str("  \"max_application_payload_length\": 4072,\n");
    output.push_str("  \"max_update_record_length\": 4024,\n");
    output.push_str("  \"certificate_control_public_key_hex\": \"");
    output.push_str(&hex(control_public_key));
    output.push_str("\",\n  \"certificate_manifest_hex\": \"");
    output.push_str(&hex(certificate_manifest));
    output.push_str("\",\n");
    output.push_str("  \"frames\": [\n");
    for (index, vector) in frames.iter().enumerate() {
        render_frame(&mut output, vector, "    ");
        output.push_str(if index == frames.len().saturating_sub(1) { "\n" } else { ",\n" });
    }
    output.push_str("  ],\n  \"invalid_payloads\": [\n");
    for (index, vector) in invalid_payloads.iter().enumerate() {
        output.push_str("    {\"expected_error\":\"");
        output.push_str(vector.expected_error);
        output.push_str("\",\"vector\":");
        render_frame(&mut output, &vector.frame, "");
        output.push('}');
        output.push_str(if index == invalid_payloads.len().saturating_sub(1) {
            "\n"
        } else {
            ",\n"
        });
    }
    output.push_str("  ],\n  \"invalid_frames\": [\n");
    for (index, vector) in invalid_frames.iter().enumerate() {
        output.push_str("    {\"name\":\"");
        output.push_str(vector.name);
        output.push_str("\",\"expected_error\":\"");
        output.push_str(vector.expected_error);
        output.push_str("\",\"frame_hex\":\"");
        output.push_str(&hex(&vector.frame));
        output.push_str("\"}");
        output.push_str(if index == invalid_frames.len().saturating_sub(1) { "\n" } else { ",\n" });
    }
    output.push_str("  ]\n}\n");
    output
}

fn render_frame(output: &mut String, vector: &FrameVector, indent: &str) {
    output.push_str(indent);
    output.push_str("{\"name\":\"");
    output.push_str(vector.name);
    output.push_str("\",\"category\":\"");
    output.push_str(vector.category);
    output.push_str("\",\"message_type\":");
    output.push_str(&vector.message_type.to_string());
    output.push_str(",\"correlation_id_hex\":\"");
    output.push_str(&hex(&vector.correlation_id));
    output.push_str("\",\"payload_hex\":\"");
    output.push_str(&hex(&vector.payload));
    output.push_str("\",\"frame_hex\":\"");
    output.push_str(&hex(&vector.frame));
    output.push_str("\"}");
}

fn hex(bytes: &[u8]) -> String {
    let mut encoded = String::with_capacity(bytes.len().saturating_mul(2));
    for byte in bytes {
        encoded.push(hex_digit(byte >> 4));
        encoded.push(hex_digit(byte & 0x0f));
    }
    encoded
}

fn hex_digit(nibble: u8) -> char {
    char::from_digit(u32::from(nibble), 16).unwrap_or('?')
}

/// Golden-vector generation failure.
#[derive(Debug)]
pub struct GenerateError {
    message: String,
}

impl GenerateError {
    fn new(message: impl Into<String>) -> Self {
        Self { message: message.into() }
    }
}

impl fmt::Display for GenerateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.message)
    }
}

impl std::error::Error for GenerateError {}

impl From<std::io::Error> for GenerateError {
    fn from(error: std::io::Error) -> Self {
        Self::new(error.to_string())
    }
}

impl From<renee_types::LoroMetadataError> for GenerateError {
    fn from(error: renee_types::LoroMetadataError) -> Self {
        Self::new(error.to_string())
    }
}

impl From<renee_wire::CapabilityCodecError> for GenerateError {
    fn from(error: renee_wire::CapabilityCodecError) -> Self {
        Self::new(error.to_string())
    }
}

impl From<renee_wire::UpdateCodecError> for GenerateError {
    fn from(error: renee_wire::UpdateCodecError) -> Self {
        Self::new(error.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::generate;

    #[test]
    fn checked_in_corpus_matches_renee_encoders() {
        let generated = generate().expect("golden vectors must generate");
        assert_eq!(
            generated,
            include_str!("../../../wire-vectors/v1.json"),
            "run `cargo run -p renee-wire-vectors -- --write`"
        );
    }
}
