[package]
name = "renee-gatewayd"
description = "Public WebTransport gateway daemon for Renee"
keywords = ["networking", "server", "webtransport"]
categories = ["network-programming"]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
renee-wire = { path = "../renee-wire" }
ring.workspace = true
time.workspace = true
tokio.workspace = true
wtransport.workspace = true

[lints]
workspace = true
