[package]
name = "renee-sessiond"
description = "Connection session daemon for Renee"
keywords = ["isolation", "server", "session"]
categories = ["network-programming"]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
renee-wire = { path = "../renee-wire" }
tokio.workspace = true

[lints]
workspace = true
