[package]
name = "renee-wire"
description = "Experimental public wire profile owned by Renee"
keywords = ["protocol", "serialization", "webtransport"]
categories = ["encoding", "network-programming"]
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
tokio.workspace = true

[lints]
workspace = true
